name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
    steps:
    - task: CmdLine@2
      displayName: Install newman
      inputs:
        script: 'sudo npm install -g newman  '
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: CmdLine@2
      displayName: Testing collection
      continueOnError: true
      inputs:
        script: 'newman run starterapis.json'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    